### ISSUE TITLE
RubyDataScience

### ISSUE THREAD

**Issue by arbox** [mrkn/enumerable-statistics#1]
Dear Kenta,

I've recently added your project to our RubyDataScience list: https://github.com/arbox/data-science-with-ruby

I wonder if you want to participate in the Ruby for Data Science network. You could do this in a very simple step by adding the `rubydatascience` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by mrkn** [comment]
@arbox I've done.

**Comment by arbox** [comment]
Thank you! Let's promote Ruby for scientific related tasks together :)
