### ISSUE TITLE
Where can I get more information about the edge detection algorithm?

### ISSUE THREAD

**Issue by schneems** [mrkn/enumerable-statistics#24]
I really appreciate your library. I opened up a PR #23. While I wait I was considering porting the histogram code to pure Ruby. I was wondering where the edge detection algorithm came from or if you have any more information about it https://github.com/mrkn/enumerable-statistics/blob/20e3e9f04a4918c62bcc8d88b217e339fdbe87a0/ext/enumerable/statistics/extension/statistics.c#L2159

Thanks again for this library!

**Comment by mrkn** [comment]
Sorry for missing this issue.  This algorithm isn't my original.  I should describe what I referred to write it but I forgot to do so.  Presumably, it is Julia, scipy, or numpy.  I'll tell you when I recall it.
